name: Java CI
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '11' ]
    name: Test on Java ${{matrix.java}}
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK ${{matrix.java}}
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{matrix.java}}
      - name: Build jar with Gradle
        run: ./gradlew jar
      - name: Run tests with Gradle
        run: ./gradlew test jacocoTestReport
      - name: Upload Jar
        uses: actions/upload-artifact@v2
        with:
          name: Jar
          path: build/libs
      - name: Upload Reports
        uses: actions/upload-artifact@v2
        with:
          name: Reports
          path: build/reports
